name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: ./.github/workflows/check-formatting.yml
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml

  mergeable:
    if: always()
    needs:
      - lint
      - format
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs)}}

  npm:
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    needs: [mergeable]
    uses: ./.github/workflows/npm.yml
    secrets: inherit
